(function(){
  "use strict";
  if(window.__lakeshoreMyTeamPageLoaded)return;
  window.__lakeshoreMyTeamPageLoaded=true;
  if(!/^\/myteam\/?$/.test(location.pathname))return;

  var ROOT="https://iamtpolk.github.io/lakeshore-site-public/assets/team/";
  var people=[
    {name:"Tyler Polk",role:"Founder of Lakeshore Team, Brokered by eXp Realty",license:"995706344",region:"South Louisiana",image:"tyler-polk.webp",position:"center bottom",bio:"Tyler Polk is the founder of Lakeshore Team, brokered by eXp Realty, serving agents and clients across South Louisiana with a focus on growth, leadership, systems, and real relationships. He specializes in residential, commercial, investment, and distressed properties.",phone:"+13372414963",email:"tyler.polk@exprealty.com",connect:"https://popl.co/profile/tpolktherealtor",instagram:"https://www.instagram.com/tpolk_therealtor/",facebook:"https://www.facebook.com/tyler.polk.908"},
    {name:"Chelsea Porter",role:"Residential Specialist",license:"995718627",region:"Acadiana",image:"chelsea-porter.webp",position:"center 38%",bio:"Chelsea is passionate about delivering a seamless, stress-free real estate experience. Known for her organization, attention to detail, and commitment to exceptional service, she is dedicated to helping every client feel confident from start to finish.",phone:"+13373240588",email:"chelsea.porter@exprealty.com",connect:"https://m.me/61582528467689",instagram:"https://www.instagram.com/cporter_realtor",facebook:"https://www.facebook.com/profile.php?id=61582528467689"},
    {name:"Madeleine Davis",role:"Residential Specialist / Marketing Genius",license:"995706355",region:"Southwest Louisiana",image:"madeleine-davis.webp",position:"center 35%",bio:"Madeleine guides buyers and sellers throughout Southwest Louisiana with a thoughtful and personalized approach. Friendly, responsive, and dedicated, she believes real estate is about more than transactions—it is about helping people navigate important life moments.",connect:"https://hihello.com/p/593bf9e9-8a27-4b7d-8e6a-60473c6a7fbf",instagram:"https://www.instagram.com/movingwmadeleine",facebook:"https://www.facebook.com/share/1DPDneSKJH/?mibextid=wwXIfr"}
  ];
  var icons={phone:'<svg viewBox="0 0 24 24"><path d="M6.6 2.8 3.8 5.6c-.8.8-.9 2.1-.3 3.1 2.7 5 6.8 9.1 11.8 11.8 1 .6 2.3.5 3.1-.3l2.8-2.8-4.6-4.6-2.2 2.2a15.4 15.4 0 0 1-5.4-5.4l2.2-2.2-4.6-4.6Z"/></svg>',email:'<svg viewBox="0 0 24 24"><path d="M3 5h18v14H3V5Zm2 2v.5l7 5 7-5V7H5Zm14 10V9.9l-7 5-7-5V17h14Z"/></svg>',instagram:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="12" cy="12" r="4.2" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="17.5" cy="6.5" r="1"/></svg>',facebook:'<svg viewBox="0 0 24 24"><path d="M14.3 8.1h3.1V4.4c-.5-.1-2.2-.2-4.1-.2-4 0-6.7 2.4-6.7 6.9V15H2.3v4.2h4.3V24h5.1v-4.8h4.2l.7-4.2h-4.9v-3.5c0-1.2.3-3.4 2.6-3.4Z"/></svg>'};
  function esc(v){return String(v).replace(/[&<>\"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c];});}
  function action(type,href,label){return '<a class="lst-myteam-icon lst-myteam-icon--'+type+'" href="'+esc(href)+'"'+(/^https?:/.test(href)?' target="_blank" rel="noopener noreferrer"':'')+' aria-label="'+esc(label)+'">'+icons[type]+'</a>';}
  function card(p,i){var links='';if(p.phone)links+=action('phone','tel:'+p.phone,'Call '+p.name);if(p.email)links+=action('email','mailto:'+p.email,'Email '+p.name);links+=action('instagram',p.instagram,p.name+' on Instagram')+action('facebook',p.facebook,p.name+' on Facebook');return '<article class="lst-myteam-card"><div class="lst-myteam-photo"><span class="lst-myteam-number">0'+(i+1)+'</span><img src="'+ROOT+p.image+'" alt="'+esc(p.name+', '+p.role)+'" loading="lazy" decoding="async" style="object-position:'+p.position+'"></div><div class="lst-myteam-copy"><p class="lst-myteam-region">'+esc(p.region)+'</p><h2>'+esc(p.name)+'</h2><p class="lst-myteam-role">'+esc(p.role)+'</p><p class="lst-myteam-license">REALTOR &middot; License '+esc(p.license)+'</p><p class="lst-myteam-bio">'+esc(p.bio)+'</p><div class="lst-myteam-foot"><div class="lst-myteam-icons">'+links+'</div><a class="lst-myteam-connect" href="'+esc(p.connect)+'" target="_blank" rel="noopener noreferrer">Connect <span aria-hidden="true">&rarr;</span></a></div></div></article>';}
  var css=`
    body:not(.home) .md-banner,body:not(.home) main>.md-team{display:none!important}
    #lst-myteam-page{position:relative;overflow:hidden;color:#202322;background:#f8f7f2}
    #lst-myteam-page *{box-sizing:border-box}
    .lst-myteam-hero{position:relative;overflow:hidden;padding:clamp(82px,9vw,142px) 24px clamp(70px,8vw,112px);color:#f8f7f2;text-align:center;background:radial-gradient(circle at 86% 8%,rgba(185,144,82,.22),transparent 30%),linear-gradient(145deg,#202322,#151817 65%,#202322)}
    .lst-myteam-hero::before{content:"";position:absolute;inset:0;pointer-events:none;background:repeating-radial-gradient(ellipse at 88% 12%,transparent 0 34px,rgba(185,144,82,.055) 35px 36px,transparent 37px 65px)}
    .lst-myteam-hero>*{position:relative;z-index:1}
    .lst-myteam-kicker{margin:0 0 14px;color:#d7c582;font:700 11px/1.2 Inter,Arial,sans-serif;letter-spacing:.22em;text-transform:uppercase}
    .lst-myteam-hero h1{max-width:980px;margin:0 auto;color:#fff;font:500 clamp(48px,6.4vw,88px)/.98 Georgia,serif;letter-spacing:-.04em}
    .lst-myteam-hero p:last-child{max-width:690px;margin:22px auto 0;color:rgba(248,247,242,.72);font:400 16px/1.72 Inter,Arial,sans-serif}
    .lst-myteam-list{max-width:1320px;margin:0 auto;padding:clamp(70px,8vw,116px) 24px}
    .lst-myteam-card{display:grid;overflow:hidden;margin-bottom:30px;grid-template-columns:minmax(300px,.82fr) minmax(420px,1.18fr);border:1px solid rgba(36,15,14,.13);border-radius:28px;background:rgba(255,255,255,.72);box-shadow:0 24px 60px rgba(36,15,14,.1)}
    .lst-myteam-card:nth-child(even){grid-template-columns:minmax(420px,1.18fr) minmax(300px,.82fr)}.lst-myteam-card:nth-child(even) .lst-myteam-photo{order:2}.lst-myteam-card:nth-child(even) .lst-myteam-copy{order:1}
    .lst-myteam-photo{position:relative;min-height:530px;overflow:hidden;background:#7d6e4e}.lst-myteam-photo::after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 62%,rgba(36,15,14,.48))}
    .lst-myteam-photo img{display:block!important;width:100%!important;height:100%!important;object-fit:cover!important;visibility:visible!important;opacity:1!important;transition:transform .5s ease}.lst-myteam-card:hover img{transform:scale(1.025)}
    .lst-myteam-number{position:absolute;z-index:2;top:22px;left:24px;color:rgba(255,255,255,.85);font:700 11px/1 Inter,Arial,sans-serif;letter-spacing:.18em}
    .lst-myteam-copy{display:flex;flex-direction:column;justify-content:center;padding:clamp(34px,5vw,70px);background:radial-gradient(circle at 100% 0,rgba(185,144,82,.15),transparent 34%),linear-gradient(145deg,#341614,#240f0e);color:#f8f7f2}
    .lst-myteam-region{margin:0 0 12px;color:#d7c582;font:700 10px/1.3 Inter,Arial,sans-serif;letter-spacing:.16em;text-transform:uppercase}.lst-myteam-copy h2{margin:0;color:#fff;font:500 clamp(36px,4vw,58px)/1 Georgia,serif;letter-spacing:-.03em}
    .lst-myteam-role{margin:12px 0 5px;color:rgba(248,247,242,.9);font:700 11px/1.5 Inter,Arial,sans-serif;letter-spacing:.055em;text-transform:uppercase}.lst-myteam-license{margin:0;color:rgba(248,247,242,.52);font:500 10px/1.5 Inter,Arial,sans-serif}
    .lst-myteam-bio{max-width:64ch;margin:24px 0 0;color:rgba(248,247,242,.74);font:400 14px/1.75 Inter,Arial,sans-serif}.lst-myteam-foot{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-top:30px;padding-top:20px;border-top:1px solid rgba(215,197,130,.25)}
    .lst-myteam-icons{display:flex;flex-wrap:wrap;gap:8px}.lst-myteam-icon{display:inline-flex;width:38px;height:38px;align-items:center;justify-content:center;border:1px solid rgba(255,255,255,.17);border-radius:11px;background:rgba(255,255,255,.08)}.lst-myteam-icon svg{width:17px;height:17px;fill:currentColor}.lst-myteam-icon--phone{color:#55c271}.lst-myteam-icon--email{color:#d7c582}.lst-myteam-icon--instagram{color:#d62976}.lst-myteam-icon--facebook{color:#1877f2}
    .lst-myteam-connect{display:inline-flex;min-height:44px;align-items:center;justify-content:center;gap:10px;padding:0 18px;color:#240f0e!important;border-radius:12px;background:linear-gradient(135deg,#d7c582,#b89052);font:800 10px/1 Inter,Arial,sans-serif;letter-spacing:.08em;text-decoration:none!important;text-transform:uppercase}
    .lst-myteam-cta{padding:clamp(70px,8vw,110px) 24px;text-align:center;background:linear-gradient(135deg,#e9e0ce,#f8f7f2)}.lst-myteam-cta h2{max-width:780px;margin:0 auto;color:#240f0e;font:500 clamp(40px,5vw,68px)/1.02 Georgia,serif;letter-spacing:-.035em}.lst-myteam-cta p{max-width:600px;margin:18px auto 26px;color:#625d54;font:400 15px/1.7 Inter,Arial,sans-serif}.lst-myteam-cta a{display:inline-flex;min-height:50px;align-items:center;justify-content:center;padding:0 24px;color:#fff!important;border-radius:13px;background:#240f0e;font:800 11px/1 Inter,Arial,sans-serif;letter-spacing:.09em;text-decoration:none!important;text-transform:uppercase}
    @media(max-width:860px){.lst-myteam-card,.lst-myteam-card:nth-child(even){grid-template-columns:1fr;max-width:620px;margin:0 auto 24px}.lst-myteam-card:nth-child(even) .lst-myteam-photo,.lst-myteam-card:nth-child(even) .lst-myteam-copy{order:initial}.lst-myteam-photo{min-height:470px}.lst-myteam-copy{padding:38px 30px}}
    @media(max-width:560px){.lst-myteam-hero{padding:68px 18px 62px}.lst-myteam-hero h1{font-size:47px}.lst-myteam-list{padding:58px 16px}.lst-myteam-photo{min-height:400px}.lst-myteam-copy{padding:30px 20px}.lst-myteam-foot{align-items:flex-end}.lst-myteam-connect{padding:0 14px}}
    @media(prefers-reduced-motion:reduce){#lst-myteam-page *{transition:none!important}}
  `;
  function build(){if(document.getElementById('lst-myteam-page'))return;var footer=document.querySelector('main>.md-footer'),team=document.querySelector('main>.md-team');if(!footer||!team||!footer.parentNode)return;var section=document.createElement('section');section.id='lst-myteam-page';section.setAttribute('aria-labelledby','lst-myteam-title');section.innerHTML='<header class="lst-myteam-hero"><p class="lst-myteam-kicker">Meet Lakeshore Team</p><h1 id="lst-myteam-title">Local expertise. One shared standard.</h1><p>Four South Louisiana real estate professionals bringing clear communication, thoughtful strategy, and dependable guidance to every move.</p></header><div class="lst-myteam-list">'+people.map(card).join('')+'</div><div class="lst-myteam-cta"><h2>Not sure who is the right fit?</h2><p>Tell us what you are planning and we will connect you with the Lakeshore Team specialist best suited to help.</p><a href="/contact">Start the Conversation &nbsp;&rarr;</a></div>';footer.parentNode.insertBefore(section,footer);}
  if(!document.getElementById('lakeshore-myteam-styles')){var s=document.createElement('style');s.id='lakeshore-myteam-styles';s.textContent=css;document.head.appendChild(s)}build();new MutationObserver(build).observe(document.documentElement,{childList:true,subtree:true});
})();
